In [59]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [107]:
dataset = pd.read_csv('train_data.csv')
dataset.head()

TrainNo               TrainName  Type  Distance  Region  Day  DelayInMin
0    12004  Lucknow Swarn Shatabdi     0         0       4    1          12
1    12004  Lucknow Swarn Shatabdi     0         0       4    2          26
2    12004  Lucknow Swarn Shatabdi     0         0       4    3          22
3    12004  Lucknow Swarn Shatabdi     0         0       4    4          16
4    12004  Lucknow Swarn Shatabdi     0         0       4    5          27

In [108]:
# dataset.drop(columns=['Region'])
del dataset['Region']
dataset

TrainNo               TrainName  Type  Distance  Day  DelayInMin
0      12004  Lucknow Swarn Shatabdi     0         0    1          12
1      12004  Lucknow Swarn Shatabdi     0         0    2          26
2      12004  Lucknow Swarn Shatabdi     0         0    3          22
3      12004  Lucknow Swarn Shatabdi     0         0    4          16
4      12004  Lucknow Swarn Shatabdi     0         0    5          27
..       ...                     ...   ...       ...  ...         ...
449    12529      north east express     1         1    3         323
450    12530      north east express     1         1    4         278
451    12531      north east express     1         1    5         367
452    12532      north east express     1         1    6         390
453    12533      north east express     1         1    7         430

[454 rows x 6 columns]

In [109]:
X = dataset.iloc[:, 2:5].values
y = dataset.iloc[:, -1].values

In [111]:
X[53]

array([1, 0, 5], dtype=int64)

In [112]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [114]:
X[53]

array([0., 0., 0., 0., 1., 0., 0., 1., 0.])

In [115]:
y[53]

45

In [116]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [117]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [118]:
print(X_test[1])

[0. 0. 0. 0. 0. 1. 0. 1. 0.]


In [121]:
y_pred = regressor.predict(X_test)
print(y_pred)

[ 57.64  57.64  25.78  -8.68 -20.47  31.89  -6.25  95.85 107.38  55.21
  57.72 119.17  55.28 -32.    25.78 -38.11  55.21 -32.   -25.64  43.49
 121.6   57.72 107.38  31.89  43.41  43.41  -6.25  89.74  25.78 -25.64
  31.96  45.89  57.64  45.81  55.21  43.49  25.85 -25.64  89.74  38.32
 119.17  -6.25  43.41  55.21  31.96 107.38 109.78 109.78  25.78  31.89
 121.6   55.28 119.17  -8.68 109.78  31.89 107.38 -32.    43.41 102.21
 121.6  119.17 -20.47  25.78  38.32 107.38 121.6   45.89  -6.25  38.25
 119.17 119.17 -25.64  45.81  38.25 109.78  31.89 119.17  45.81  95.85
  31.96  31.96 109.78 102.21  43.41 -25.64  95.85  38.32 107.38  25.85
  25.78  38.25  43.41  -6.25  38.25  38.25 109.78 -20.47 102.21 -18.07
 107.38  25.78 -32.   -32.    -6.25 107.38  95.85  55.21 -38.11  95.85
  57.72 -32.    57.64 107.38  -8.68  95.85  38.25 -38.11  45.89 -32.
  89.74 109.78 107.38  57.64  31.89  55.21  89.74  89.74  43.41  43.49
  43.49  89.74  89.74  89.74  95.85  -8.68  38.25 102.21 107.38  45.81
 119.17 

In [125]:
x = [[0,0,0,0,0,1,0,1,0]]
print(regressor.predict(x))

[57.64]


In [126]:
x = [[0,0,0,0,0,1,0,1,1]]
print(regressor.predict(x))

[121.6]


In [127]:
x = [[0,0,1,0,0,0,0,0,0]]
print(regressor.predict(x))

[-18.07]


In [137]:
x = [[0,0,0,0,0,0,1,1,1]]
print(regressor.predict(x))

[119.17]


In [138]:
x = [[0,0,0,0,0,0,1,1,1]]
print(regressor.predict(x))

[119.17]


In [139]:
x = [[0,0,0,0,0,1,0,1,1]]
print(regressor.predict(x))

[121.6]
